# Generated by Django 3.0.7 on 2020-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producter',
            field=models.CharField(max_length=200, verbose_name='产品经理'),
        ),
    ]
